### PR TITLE
Added Structure to project

### PR DESCRIPTION
**Pull request by samritbk**
Added some basic structure and page components to the project. I am fairly new to react so please critic me as much as you can.

### CODE REVIEW

**Comment by samritbk** [comment]
@dbernar1  package-lock.json shows the structure of how the NPM packages were compiled to run the application. 
I put the empty CSS file just so that we have a structure to add the CSS data in 1 file. It will prevent merge conflicts.

**Comment by samritbk** [comment]
@dbernar1  And the first commit about package-lock.json  was reverted in the second commit as I felt like it would be better to have it there.

**Comment by kleyson** [comment]
Thanks @samritbk.

**Comment by dbernar1** [comment]
Hey guys - I just noticed that there was already a yarn.lock file in the repository. I think it might make sense to pick one of them and get rid of the other.

Does that make sense, or is it better to have both?

**Comment by samritbk** [comment]
I personally use yarn but sone people may be using npm only and may not know yarn. I think we should have it for now and towards the end we can get rid of them. Good thing is if you have yarn.lock the package-lock.json is ignored. Some one correct me if I am wrong.

**Comment by dbernar1** [comment]
Sounds good thanks.

**Pull request merged**
